<!DOCTYPE html>
<html lang="en">
<head>
<title>Phorum Development Prototype</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/bootstrap/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>
    <link href="/bootstrap/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Project name</a>
      <div class="btn-group pull-right">
        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
          <i class="icon-user"></i> Other Stuff
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><a href="#">Entry 1</a></li>
          <li class="divider"></li>
          <li><a href="#">Entry 2</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid">
   <div class="row-fluid">
     <div class="span3">
         <div class="well sidebar-nav">
             See the sidemenu
         </div>

     </div><!--/span-->
     <div class="span9">
         <?php if (count($this->messages)) : ?>
         <?php foreach ($this->messages as $message) : ?>
             <div class="alert">
               <button class="close" data-dismiss="alert">×</button>
               <strong>Attention!</strong> <?php echo $this->escape($message); ?>
             </div>
         <?php endforeach; ?>

         <?php endif; ?>

      <?php echo $this->layout()->content; ?>
     </div><!--/span-->
   </div><!--/row-->

   <hr>

   <footer>
     <p>&copy; Phorum Development Team 2013</p>
   </footer>

 </div><!--/.fluid-container-->
<script src="/bootstrap/js/jquery.min.js"></script>
<script src="/bootstrap/js/bootstrap.min.js"></script>

</body>
</html>
